#ifndef _CLX_DRIVER_COMMON_H_
#define _CLX_DRIVER_COMMON_H_

#define CLX_SYSEEPROM_BUS 0
#define CLX_SYSEEPROM_ADDR 0x50

#define CLX_PCA9548_ADDR 0x70
#define CLX_PCA9548_CHANNEL_IDROM 0x40

#define CLX_FAN_BUS 6
#define CLX_FAN_ADDR 0x60

#define CLX_FAN_BUS 6
#define CLX_FAN_ADDR 0x60
#endif //_CLX_DRIVER_COMMON_H_
