# Pegatron Platform modules
PEGATRON_PLATFORM_MODULE_VERSION = 1.0.0
export PEGATRON_PLATFORM_MODULE_VERSION

PEGATRON_FN8656_BNF_PLATFORM_MODULE = sonic-platform-pegatron-fn8656-bnf_$(PEGATRON_PLATFORM_MODULE_VERSION)_amd64.deb
$(PEGATRON_FN8656_BNF_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-pegatron
$(PEGATRON_FN8656_BNF_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(PEGATRON_FN8656_BNF_PLATFORM_MODULE)_PLATFORM = x86_64-pegatron_fn8656_bnf-r0
SONIC_DPKG_DEBS += $(PEGATRON_FN8656_BNF_PLATFORM_MODULE)

$(eval $(call add_extra_package,$(PEGATRON_FN8656_BNF_PLATFORM_MODULE)))
