# Pegatron Platform modules
CLOUNIX_PLATFORM_MODULE_VERSION = 1.0.0
export CLOUNIX_PLATFORM_MODULE_VERSION
ifeq ($(CONFIGURED_ARCH), amd64)
TARGET_ARCH = x86_64
else
TARGET_ARCH = $(CONFIGURED_ARCH)
endif
CLOUNIX_CLX8000_48C8D_PLATFORM_MODULE = sonic-platform-clounix-clx8000-48c8d_$(CLOUNIX_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(CLOUNIX_CLX8000_48C8D_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-clounix
$(CLOUNIX_CLX8000_48C8D_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(CLOUNIX_CLX8000_48C8D_PLATFORM_MODULE)_PLATFORM = $(TARGET_ARCH)-clounix_clx8000_48c8d-r0
SONIC_DPKG_DEBS += $(CLOUNIX_CLX8000_48C8D_PLATFORM_MODULE)
